### ISSUE TITLE
Ctrl + middle mouse click

### ISSUE THREAD

**Issue by x1p** [Ruinscraft/Panilla#10] opened 2019-05-01 13:43 UTC
When a player copies a written sign or a hopper by holding ctrl + middle mouse button, it copies NBT data. It  then refuses to be placed.
```
[Panilla] Packet from CrashTestPuppet (PacketPlayInSetCreativeSlot) was dropped because NBT tag BlockEntityTag failed checks
[Panilla] Packet from CrashTestPuppet (PacketPlayInSetCreativeSlot) was dropped because NBT tag BlockEntityTag failed checks
```
The nbt block data:
![Screenshot_20190501_152541](https://user-images.githubusercontent.com/28690790/57019197-147ffd00-6c26-11e9-82bb-5f81e0731493.png)
When the players rejoins, the items are gone. From my point of view, this data is not very illegal. But I could be wrong. If so, why not strip the nbt data?

The gamemode is creative, strictness average. (Lenient was unable to filter hacked items like speed sticks etc.)

**Comment by dextonanderson** [comment] 2019-05-01 19:18
I have adjusted the way BlockEntityTag checks work in e2bed213feab79261c42c93386117d3619ff5b1c.

> BlockEntityTag explanation:
> 
> strictness: lenient will allow any item to contain the tag. Panilla will check items within the tag, eg: checking the items within a hopper/chest/ShulkerBox/etc that has BlockEntityTag.
> 
> strictness: average same as lenient
> 
> strictness: strict will only allow ShulkerBox items to contain the tag (the way it is in survival-mode), as well as checking the items within the ShulkerBox.

A new version `1.2.2` is available on SpigotMC. Please let me know if this works for you.

**Comment by x1p** [comment] 2019-05-01 19:44
The sign is allowed to be placed as if the sign was empty. So the text is lost.
Without Panilla, the placed sign is instantly filled with the copied text.
Since my game mode is creative, it's really no big deal.

**Comment by dextonanderson** [comment] 2019-05-01 19:46
Try `strictness: average`, signs with prefilled text should be allowed with that strictness.

**Comment by x1p** [comment] 2019-05-01 19:56
> The gamemode is creative, strictness average. (Lenient was unable to filter hacked items like speed sticks etc.)

I still am in average.
No error or warning on the console, text is still on the sign when I have it in the inventory.
When the sign is placed, it acts as if you place a new default sign.

**Comment by dextonanderson** [comment] 2019-05-01 20:04
In this case, I don't believe this issue would be caused by Panilla. I am able to CTRL + middle click on a sign, while in average strictness, and place it with prefilled text.

**Comment by dextonanderson** [comment] 2019-05-01 20:06
Actually, disregard that last comment, I was able to replicate.

**Comment by dextonanderson** [comment] 2019-05-01 20:32
@x1p This is actually a feature of vanilla Minecraft. Non-ops are not allowed to place prefilled signs I suppose.

To replicate (at least on 1.13.2):
1. Run a fresh CraftBukkit server with no plugins
2. Obtain creative mode (without OP)
3. Place a sign and fill in some text
4. CTRL + middle click said sign
5. Place sign and notice it brings open the edit screen with no text

If you had been OP, it allows you to place prefilled text.

**Comment by x1p** [comment] 2019-05-01 20:40
No problem. But still strange. I'm running latest 1.13.2 paper and this behavior is without OP. I'll do some more tests.

**Comment by dextonanderson** [comment] 2019-05-01 20:41
Yes, I never knew this was a feature. I am closing this issue since it is not related to Panilla

**Closed by dextonanderson** 2019-05-01 20:41 UTC
