### ISSUE TITLE
Chests with NBT

### ISSUE THREAD

**Issue by x1p** [Ruinscraft/Panilla#32] opened 2019-11-30 11:50 UTC
Player placed (double) chests containing chests with NBT tags:
```
->: BlockEntityTag (Compound)
->: Items (List)
->: BlockEntityTag (Compound)
->: Items (List)
- {Slot:0b,id:"minecraft:gold_block",Count:64b}
- {Slot:1b,id:"minecraft:gold_block",Count:64b}
- {Slot:2b,id:"minecraft:gold_block",Count:64b}
- {Slot:3b,id:"minecraft:gold_block",Count:64b}
- {Slot:4b,id:"minecraft:gold_block",Count:64b}
- {Slot:5b,id:"minecraft:gold_block",Count:64b}
- {Slot:6b,id:"minecraft:gold_block",Count:64b}
- {Slot:7b,id:"minecraft:gold_block",Count:64b}
- {Slot:8b,id:"minecraft:gold_block",Count:64b}
- {Slot:9b,id:"minecraft:gold_block",Count:64b}
- {Slot:10b,id:"minecraft:gold_block",Count:64b}
- {Slot:11b,id:"minecraft:gold_block",Count:64b}
- {Slot:12b,id:"minecraft:gold_block",Count:64b}
- {Slot:13b,id:"minecraft:gold_block",Count:64b}
- {Slot:14b,id:"minecraft:gold_block",Count:64b}
- {Slot:15b,id:"minecraft:gold_block",Count:64b}
- {Slot:16b,id:"minecraft:gold_block",Count:64b}
- {Slot:17b,id:"minecraft:gold_block",Count:64b}
- {Slot:18b,id:"minecraft:gold_block",Count:64b}
- {Slot:19b,id:"minecraft:gold_block",Count:64b}
- {Slot:20b,id:"minecraft:gold_block",Count:64b}
- {Slot:21b,id:"minecraft:gold_block",Count:64b}
- {Slot:22b,id:"minecraft:gold_block",Count:64b}
- {Slot:23b,id:"minecraft:gold_block",Count:64b}
- {Slot:24b,id:"minecraft:gold_block",Count:64b}
- {Slot:25b,id:"minecraft:gold_block",Count:64b}
- {Slot:26b,id:"minecraft:gold_block",Count:64b}
->: id (String): minecraft:chest
->: display (Compound)
->: Lore (List): {"text":"(+NBT)"}
```
Every chest contains 54 slots, every slot contains 1 stack of these chests. Each of these chests contains 27 stacks (e.g.) of gold_blocks.
It's not like this is very illegal, but a server doesn't like it. It overloads chunks and thereby kills tps

Panilla version 1.4.1

**Comment by dextonanderson** [comment] 2019-12-12 01:15
Try `1.4.2` and see if it works for you

**Comment by x1p** [comment] 2019-12-12 10:29
I'm not sure this is meant to happen when someone joins the game.
```
[11:25:27 ERROR]: Could not pass event PlayerJoinEvent to Panilla v1.4.2
java.util.NoSuchElementException: decompress
at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:1119) ~[patched_1.14.4.jar:git-Paper-235]
at io.netty.channel.DefaultChannelPipeline.replace(DefaultChannelPipeline.java:540) ~[patched_1.14.4.jar:git-Paper-235]
at com.comphenix.protocol.injector.netty.PipelineProxy.replace(PipelineProxy.java:344) ~[?:?]
at com.ruinscraft.panilla.api.io.IPlayerInjector.register(IPlayerInjector.java:38) ~[?:?]
at com.ruinscraft.panilla.bukkit.JoinQuitListener.onJoin(JoinQuitListener.java:21) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor22.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-235]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.14.4.jar:git-Paper-235]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-235]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-235]
at net.minecraft.server.v1_14_R1.PlayerList.a(PlayerList.java:191) ~[patched_1.14.4.jar:git-Paper-235]
at net.minecraft.server.v1_14_R1.LoginListener.c(LoginListener.java:174) ~[patched_1.14.4.jar:git-Paper-235]
at net.minecraft.server.v1_14_R1.LoginListener.tick(LoginListener.java:65) ~[patched_1.14.4.jar:git-Paper-235]
at net.minecraft.server.v1_14_R1.NetworkManager.a(NetworkManager.java:256) ~[patched_1.14.4.jar:git-Paper-235]
at net.minecraft.server.v1_14_R1.ServerConnection.c(ServerConnection.java:139) ~[patched_1.14.4.jar:git-Paper-235]
at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1255) ~[patched_1.14.4.jar:git-Paper-235]
at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.14.4.jar:git-Paper-235]
at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1098) ~[patched_1.14.4.jar:git-Paper-235]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925) ~[patched_1.14.4.jar:git-Paper-235]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212] 
```

**Comment by dextonanderson** [comment] 2019-12-12 12:58
@x1p Oh. Do you have compression disabled in your server.properties

**Comment by x1p** [comment] 2019-12-12 13:01
Yes, because it is handled by bungee as commonly recommended

**Comment by dextonanderson** [comment] 2019-12-12 14:07
Could you possibly also send me a player.dat file with these gold blocks in it?

I may not be able to fix this issue with Panilla, if it relates to the 1MB chunk limit. That has to be handled by the server itself and is something that, even if I do block certain NBT, can still easily be gotten around

**Comment by dextonanderson** [comment] 2019-12-12 14:08
> I'm not sure this is meant to happen when someone joins the game.
> 
> ```
> [11:25:27 ERROR]: Could not pass event PlayerJoinEvent to Panilla v1.4.2
> java.util.NoSuchElementException: decompress
> at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:1119) ~[patched_1.14.4.jar:git-Paper-235]
> at io.netty.channel.DefaultChannelPipeline.replace(DefaultChannelPipeline.java:540) ~[patched_1.14.4.jar:git-Paper-235]
> at com.comphenix.protocol.injector.netty.PipelineProxy.replace(PipelineProxy.java:344) ~[?:?]
> at com.ruinscraft.panilla.api.io.IPlayerInjector.register(IPlayerInjector.java:38) ~[?:?]
> at com.ruinscraft.panilla.bukkit.JoinQuitListener.onJoin(JoinQuitListener.java:21) ~[?:?]
> at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor22.execute(Unknown Source) ~[?:?]
> at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-235]
> at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.14.4.jar:git-Paper-235]
> at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-235]
> at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-235]
> at net.minecraft.server.v1_14_R1.PlayerList.a(PlayerList.java:191) ~[patched_1.14.4.jar:git-Paper-235]
> at net.minecraft.server.v1_14_R1.LoginListener.c(LoginListener.java:174) ~[patched_1.14.4.jar:git-Paper-235]
> at net.minecraft.server.v1_14_R1.LoginListener.tick(LoginListener.java:65) ~[patched_1.14.4.jar:git-Paper-235]
> at net.minecraft.server.v1_14_R1.NetworkManager.a(NetworkManager.java:256) ~[patched_1.14.4.jar:git-Paper-235]
> at net.minecraft.server.v1_14_R1.ServerConnection.c(ServerConnection.java:139) ~[patched_1.14.4.jar:git-Paper-235]
> at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1255) ~[patched_1.14.4.jar:git-Paper-235]
> at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.14.4.jar:git-Paper-235]
> at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1098) ~[patched_1.14.4.jar:git-Paper-235]
> at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925) ~[patched_1.14.4.jar:git-Paper-235]
> at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212] 
> ```

This is also a separate issue. See #35. Ill have a fix out shortly

**Comment by x1p** [comment] 2019-12-12 15:05
Of course
[Playerfile.zip](https://github.com/Ruinscraft/Panilla/files/3956379/Playerfile.zip)
It's zipped, but actually a dat file

**Comment by dextonanderson** [comment] 2019-12-12 20:42
I did some testing... There isn't anything in the NBT that would cause any issue. It's just a chest with gold blocks inside. NBT wouldn't be the cause of a performance issue anyhow.

I don't see any issues here that would need resolving. I believe your performance issue may come from another source.

**Comment by x1p** [comment] 2019-12-12 20:55
Ok thank you very much for investigating. It is probably a common way to overload the chunk with too much data.

Although it may seem ordinary data, I can't see why anyone would/could put a chest in your inventory with still blocks in them. It is not possible in normal survival mode. This issue was used in creative mode though.
I'll have to find another way to prevent chests containing stuff.

**Comment by dextonanderson** [comment] 2019-12-12 20:56
@x1p You can set Panilla to `strict` mode to prevent BlockEntityTag completely. `average` mode allows them because they are useful for players to create "kits" or roleplay items.

**Comment by dextonanderson** [comment] 2019-12-12 20:58
Also, Spigot does have a work around for the "overloading a chunk with too much data" bug. Again, there shouldn't be any type of performance regression due to lots of NBT items.

**Comment by x1p** [comment] 2019-12-12 21:02
At that time, the server already had tps dips because of the lag machines they were building. They've put quite a few of these double chests at a small place. Eventually, you get every server down to it's knees.
I'll test this strict mode. I don't want to destroy every roleplay altogether.

**Comment by dextonanderson** [comment] 2019-12-12 21:05
The players who were creating the lag machines were probably just experimenting with other methods of crashing players/the server. Thus, you end up finding chests with BlockEntityTag NBT on them (the NBT tag that stores the gold block item).

Ill close the issue for now. Hopefully you can find a solution to your lag problem. I will have a Panilla release out soon to address a few other bugs as well.

Thanks

**Closed by dextonanderson** 2019-12-12 21:05 UTC
